kraken
Plazmaz/leaky-repo pull request #13
Opened 2024-08-05 16:34 UTC by shadykube

2024-08-06 18:44 UTC, Plazmaz requested changes
First, thanks for the PR! These look useful. I have a few requests if possible:

1. Could you please move these into folders that match the existing organization in this repo? (Categorized into web, db, cloud, and misc, outside of keys that need to be in a specific filepath to be recognized. You could definitely keep the folders so it'd be web/coinbase/coinbase_legacy for example)
2. Could you update .leaky-meta/secrets.csv to include these secrets?

2024-08-06 18:44 UTC, Plazmaz commented on rootchpasswd/Dockerfile.rootchpasswd
> +RUN echo 'root:Asdf_123' | chpasswd && \
This is interesting. Would you expect a secret tool to detect Asdf_1234 here? That'd be something I haven't seen before.

2024-08-06 18:44 UTC, Plazmaz commented on algolia/algolia-secret.py
> +     x-algolia-api-key=a4d9d38893a8d71cd78572470a328dd4
This is not valid python code.

2024-10-09 15:25 UTC, hihihaha777 commented on algolia/algolia-secret.py
> +     x-algolia-api-key=a4d9d38893a8d71cd78572470a328dd4
lol

2024-11-19 08:49 UTC, closed without merging